# Generated by Django 5.1.3 on 2024-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='image',
            field=models.ImageField(upload_to='diseases/'),
        ),
        migrations.AlterField(
            model_name='plantdisease',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
